export const COLORS = {
  ZEST_COLOR: '#E87928',
  NEON_CARROT_COLOR: '#FF8B37',
  EMERALD_COLOR: '#47D867',
  BURNT_SIENNA_COLOR: '#EC6259',
  MISCHKA_COLOR: `#D0D0D8`,
  SHARK_COLOR: `#1C1C21`,
  MACARONI_AND_CHEESE_COLOR: `#FFAC70`,
  SEASHELL_PEACH_COLOR: `#FFF3EB`,
  WHITE_COLOR: `#FFFFFF`,
  ATHENS_GRAY: `#F5F5F7`,
};
